### PR TITLE
SCL Name uniqueness check

### LINKED ISSUE #197: Add SCL name uniqueness check (PostgreSQL)
As an Engineer
I want to be informed if my project name in CoMPAS already exists in the SCL file type
So I prevent confusion (projects with the same name)

When the users enter a name in this window:
image

and clicks on the "save" button, CoMPAS should check if the name already exists for the selected SCL type.
If the name matches an existing one an error should show.

Background:
When a new SCL File is added/updated to the PostgreSQL database we need to check if the name registered in the Private Element "SclName" (under SCL, type "compas_scl") isn't already used.
- Extended the existing Repositories (PostgreSQL/BaseX) with a method to check if a name isn't already used. 
- In the Service layer first check if the value from the private has changed (update only). 
If not changed no check is needed. 
If changed use the new method to check if the (new) name isn't already used. If already used throw a Exception and stop processing the SCL File.
- For the BaseX version implementation of the method for now just always return that the name is unique, other issue #203 will implement this version.
- For the PostgreSQL version execute a query to retrieve the names of all the latest versions and check if the (new) name isn't already used by a other SCL File.

### PR DESCRIPTION
**Pull request by Flurb**
Closes #197

### CODE REVIEW

File: repository-postgresql/src/main/java/org/lfenergy/compas/scl/data/repository/postgresql/CompasSclDataPostgreSQLRepository.java [hunk 1]
```diff
@@ -155,6 +155,29 @@ public String findByUUID(SclFileType type, UUID id, Version version) {
         }
     }
 
+    @Override
+    public boolean hasDuplicateSclName(SclFileType type, String name) {
+        var sql = "SELECT DISTINCT ON (id) m.* "
+                + "FROM scl_file m "
```
Comment (dlabordus) [inline repository-postgresql/src/main/java/org/lfenergy/compas/scl/data/repository/postgresql/CompasSclDataPostgreSQLRepository.java:161]: There constants for parts of the query to prevent duplicate code messages in the future.

File: repository-postgresql/src/main/java/org/lfenergy/compas/scl/data/repository/postgresql/CompasSclDataPostgreSQLRepository.java [hunk 2]
```diff
@@ -155,6 +155,29 @@ public String findByUUID(SclFileType type, UUID id, Version version) {
...
+
+            try (var resultSet = stmt.executeQuery()) {
+                while (resultSet.next()) {
+                    var usedName = resultSet.getString(NAME_FIELD);
+                    if (usedName.equals(name)) return true;
+                }
+            }
+            return false;
+        } catch (SQLException exp) {
+            throw new CompasSclDataServiceException(POSTGRES_SELECT_ERROR_CODE, "Error select meta info from database!", exp);
```
Comment (dlabordus) [inline repository-postgresql/src/main/java/org/lfenergy/compas/scl/data/repository/postgresql/CompasSclDataPostgreSQLRepository.java:177]: The message is probably copied from a other method. :-)

File: repository-postgresql/src/test/java/org/lfenergy/compas/scl/data/repository/postgresql/CompasSclDataPostgreSQLRepositoryTest.java [hunk 3]
```diff
@@ -22,4 +28,18 @@ protected CompasSclDataRepository getRepository() {
     void beforeEach() {
         repository = new CompasSclDataPostgreSQLRepository(PostgreSQLServerJUnitExtension.getDataSource());
     }
+
+    /**
```
Comment (dlabordus) [inline repository-postgresql/src/test/java/org/lfenergy/compas/scl/data/repository/postgresql/CompasSclDataPostgreSQLRepositoryTest.java:32]: Don't think you should make it Java Doc, but just a comment starting with // or /* */

File: repository/src/main/java/org/lfenergy/compas/scl/data/repository/CompasSclDataRepository.java [hunk 4]
```diff
@@ -70,6 +70,16 @@ public interface CompasSclDataRepository {
     @Transactional(SUPPORTS)
     String findByUUID(SclFileType type, UUID id, Version version);
 
+    /**
+     * Return the specific version of a specific SCL Entry.
+     *
+     * @param type    The type of SCL to search for the specific SCL.
+     * @param id      The ID of the SCL to search for.
```
Comment (dlabordus) [inline repository/src/main/java/org/lfenergy/compas/scl/data/repository/CompasSclDataRepository.java:77]: Param doesn't exists.

File: service/src/main/java/org/lfenergy/compas/scl/data/service/impl/CompasSclDataServiceImpl.java [hunk 5]
```diff
@@ -200,6 +213,10 @@ public void delete(SclFileType type, UUID id, Version version) {
         repository.delete(type, id, version);
     }
 
+    private boolean hasDuplicateSclName(SclFileType type, String name) {
```
Comment (dlabordus) [inline service/src/main/java/org/lfenergy/compas/scl/data/service/impl/CompasSclDataServiceImpl.java:216]: Why the need for a private method here? There is only 1 simple line in there.

**Review by dlabordus — CHANGES_REQUESTED** [review]

File: repository-postgresql/src/main/java/org/lfenergy/compas/scl/data/repository/postgresql/CompasSclDataPostgreSQLRepository.java (hunk 1 above)
Comment (Flurb) [reply repository-postgresql/src/main/java/org/lfenergy/compas/scl/data/repository/postgresql/CompasSclDataPostgreSQLRepository.java:161]: `FROM_CLAUSE` can be re used here indeed :)

File: repository-postgresql/src/main/java/org/lfenergy/compas/scl/data/repository/postgresql/CompasSclDataPostgreSQLRepository.java (hunk 2 above)
Comment (Flurb) [reply repository-postgresql/src/main/java/org/lfenergy/compas/scl/data/repository/postgresql/CompasSclDataPostgreSQLRepository.java]: Already fixed it in latest commit, changed it to `Error selecting latest versions from database!`

File: service/src/main/java/org/lfenergy/compas/scl/data/service/impl/CompasSclDataServiceImpl.java (hunk 5 above)
Comment (Flurb) [reply service/src/main/java/org/lfenergy/compas/scl/data/service/impl/CompasSclDataServiceImpl.java:216]: True, good one!

File: service/src/test/java/org/lfenergy/compas/scl/data/service/impl/CompasSclDataServiceImplTest.java [hunk 6]
```diff
@@ -148,6 +149,22 @@ void create_WhenCalledWithCompasExtension_ThenSCLReturnedWithCorrectCompasExtens
...
+
+        when(compasSclDataRepository.hasDuplicateSclName(SCL_TYPE, name)).thenReturn(true);
+        var exception = assertThrows(CompasException.class, () -> {
+            compasSclDataService.create(SCL_TYPE, name, who, comment, scl);
+        });
+        assertEquals(DUPLICATE_SCL_NAME_ERROR_CODE, exception.getErrorCode());
+        verify(compasSclDataRepository, times(1)).hasDuplicateSclName(SCL_TYPE, name);
+    }
+
     @Test
```
Comment (dlabordus) [inline service/src/test/java/org/lfenergy/compas/scl/data/service/impl/CompasSclDataServiceImplTest.java:168]: Don't we need any change/add for the update Method?

**Review by dlabordus — CHANGES_REQUESTED** [review]

**Review by dlabordus — APPROVED** [review]
